package com.softpos.sdk.security

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.Mac
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

class CryptoUnavailableException(message: String, cause: Throwable? = null) : Exception(message, cause)

/**
 * Hardware-backed cryptography for the small amount of card-derived data that reaches disk.
 *
 * Two keys, both generated inside the Android Keystore and never exportable:
 *
 *  - an AES-256-GCM key, used only when [com.softpos.sdk.SoftPosConfig.persistEncryptedPan] is
 *    switched on. That flag defaults to off, and the default build therefore never writes a
 *    recoverable PAN anywhere.
 *  - an HMAC-SHA256 key, used to derive a card fingerprint. The fingerprint groups transactions
 *    made with the same card without storing anything that can be turned back into a card number.
 *    It is one-way by construction, and because the key lives in the Keystore the digest cannot be
 *    recomputed off-device even by someone holding a candidate PAN.
 *
 * StrongBox is requested where the hardware offers it and silently downgraded to TEE-backed keys
 * otherwise, which is the normal situation on most handsets.
 */
class KeystoreCryptoService(
    private val aesAlias: String = DEFAULT_AES_ALIAS,
    private val hmacAlias: String = DEFAULT_HMAC_ALIAS,
) {

    private val keyStore: KeyStore by lazy {
        try {
            KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        } catch (e: Exception) {
            throw CryptoUnavailableException("Android Keystore is not usable on this device", e)
        }
    }

    /** True when the AES key is backed by a dedicated secure element rather than the TEE. */
    fun isStrongBoxBacked(): Boolean = strongBoxInUse

    @Volatile
    private var strongBoxInUse: Boolean = false

    // -------------------------------------------------------------------------------------------
    // AES-256-GCM
    // -------------------------------------------------------------------------------------------

    /**
     * Returns `iv || ciphertext || tag`.
     *
     * The IV is generated by the Keystore rather than supplied by the caller;
     * `setRandomizedEncryptionRequired(true)` makes reuse of an IV with the same key impossible,
     * which is the failure mode that breaks GCM outright.
     */
    fun encrypt(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(AES_TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, aesKey())
        val iv = cipher.iv
        require(iv.size == GCM_IV_LENGTH) { "unexpected GCM IV length ${iv.size}" }
        return iv + cipher.doFinal(plaintext)
    }

    fun decrypt(blob: ByteArray): ByteArray {
        require(blob.size > GCM_IV_LENGTH) { "ciphertext too short to contain an IV" }
        val cipher = Cipher.getInstance(AES_TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            aesKey(),
            GCMParameterSpec(GCM_TAG_BITS, blob, 0, GCM_IV_LENGTH),
        )
        return cipher.doFinal(blob, GCM_IV_LENGTH, blob.size - GCM_IV_LENGTH)
    }

    fun encryptToBase64(plaintext: ByteArray): String =
        Base64.encodeToString(encrypt(plaintext), Base64.NO_WRAP)

    fun decryptFromBase64(encoded: String): ByteArray =
        decrypt(Base64.decode(encoded, Base64.NO_WRAP))

    // -------------------------------------------------------------------------------------------
    // HMAC-SHA256
    // -------------------------------------------------------------------------------------------

    /**
     * Keyed digest, truncated to [FINGERPRINT_HEX_CHARS] hex characters.
     *
     * Truncation to 128 bits keeps the value short enough to display while leaving collision
     * resistance far beyond what a per-device card population needs.
     */
    fun fingerprint(data: ByteArray): String {
        val mac = Mac.getInstance(HMAC_ALGORITHM)
        mac.init(hmacKey())
        return mac.doFinal(data)
            .joinToString("") { "%02x".format(it) }
            .take(FINGERPRINT_HEX_CHARS)
    }

    // -------------------------------------------------------------------------------------------
    // Key management
    // -------------------------------------------------------------------------------------------

    private fun aesKey(): SecretKey {
        (keyStore.getEntry(aesAlias, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }
        return generateAesKey()
    }

    private fun hmacKey(): SecretKey {
        (keyStore.getEntry(hmacAlias, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }
        return generateHmacKey()
    }

    private fun generateAesKey(): SecretKey {
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            try {
                generator.init(aesSpec(strongBox = true))
                val key = generator.generateKey()
                strongBoxInUse = true
                return key
            } catch (e: StrongBoxUnavailableException) {
                // Expected on the majority of devices; fall through to a TEE-backed key.
            }
        }

        generator.init(aesSpec(strongBox = false))
        strongBoxInUse = false
        return generator.generateKey()
    }

    private fun aesSpec(strongBox: Boolean): KeyGenParameterSpec =
        KeyGenParameterSpec.Builder(
            aesAlias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(AES_KEY_BITS)
            .setRandomizedEncryptionRequired(true)
            .apply {
                if (strongBox && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                    setIsStrongBoxBacked(true)
                }
            }
            .build()

    private fun generateHmacKey(): SecretKey {
        val generator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_HMAC_SHA256,
            ANDROID_KEYSTORE,
        )
        generator.init(
            KeyGenParameterSpec.Builder(hmacAlias, KeyProperties.PURPOSE_SIGN)
                .setDigests(KeyProperties.DIGEST_SHA256)
                .build(),
        )
        return generator.generateKey()
    }

    /**
     * Deletes both keys. Every encrypted blob and every fingerprint already on disk becomes
     * permanently unreadable and unreproducible, which is the point: this is the fast path for
     * wiping card-derived data.
     */
    fun deleteKeys() {
        runCatching { keyStore.deleteEntry(aesAlias) }
        runCatching { keyStore.deleteEntry(hmacAlias) }
        strongBoxInUse = false
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val DEFAULT_AES_ALIAS = "softpos.card.aes.v1"
        const val DEFAULT_HMAC_ALIAS = "softpos.card.hmac.v1"
        const val AES_TRANSFORMATION = "AES/GCM/NoPadding"
        const val HMAC_ALGORITHM = "HmacSHA256"
        const val AES_KEY_BITS = 256
        const val GCM_IV_LENGTH = 12
        const val GCM_TAG_BITS = 128
        const val FINGERPRINT_HEX_CHARS = 32
    }
}
